@startuml

actor User
participant System
participant SocketIO
participant Database

activate User
activate System
User -> System: Chọn người dùng/tin nhắn nhóm
User -> System: Nhập tin nhắn

activate SocketIO
System -> SocketIO: Gửi tin nhắn sđến SocketIO
SocketIO --> System: Xác nhận gửi tin nhắn thành công
deactivate SocketIO

alt Đoạn chat là tin nhắn nhóm
    activate System
    System -> System: Gửi tin nhắn tới tất cả thành viên trong nhóm
else Đoạn chat là tin nhắn cá nhân
    System -> System: Gửi tin nhắn tới người dùng đích
end

System -> Database: Lưu tin nhắn vào cơ sở dữ liệu
activate Database
Database --> System: Xác nhận lưu tin nhắn thành công
deactivate Database
System --> User: Hiển thị tin nhắn đã gửi

@enduml
