@startuml


actor "User" as User
database "Database" as Database
rectangle "Rectangle" as Rectangle {
  usecase "Nhập thông tin đăng nhập" as U1
  usecase "Xác thực thông tin" as U2
  User -r- U1
  U1 .r.> U2: <<include>>
  U2 -r-> Database
}

@enduml
