@startuml
left to right direction
actor User 
database "Database" as Database
rectangle System {
    usecase "Trả về kết quả" as Result
    usecase "Tìm kiếm người dùng" as Search
    User --- Search
    Search --> Database
    Database -l-> Result
}
@enduml

